# /home/sonthl/setup/docker/fast_api_web/docker-compose.yml

services:
  web:
    build: .
    container_name: fast_api_web
    ports:
      - "8001:8000"
    volumes:
      - .:/app
      - ./static:/app/static
      - ./scripts:/opt/scripts
    environment:
      - DATABASE_URL=postgresql://fastapi:123456@postgres5444:5432/fastapi
    networks:
      - infra_net

networks:
  infra_net:
    external: true